In [1]:
!pip install numpy

You should consider upgrading via the 'C:\Users\ASUS\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [7]:
arr1=np.array(l1)

In [11]:
l2=(1,2,4,5,7)

In [12]:
np.array(l2)

array([1, 2, 4, 5, 7])

In [13]:
type(arr1)

numpy.ndarray

## 2D Array

In [17]:
array2d=(np.arange(1,10).reshape((3,3)))

In [18]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
type(array2d)

numpy.ndarray

In [20]:
array2d.dtype

dtype('int32')

In [21]:
len(array2d)

3

In [22]:
array2d.shape

(3, 3)

In [23]:
array2d.ndim

2

In [24]:
np.zeros((3,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
np.ones((3,4),dtype=complex)

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [31]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [32]:
np.linspace(1,25,20)

array([ 1.        ,  2.26315789,  3.52631579,  4.78947368,  6.05263158,
        7.31578947,  8.57894737,  9.84210526, 11.10526316, 12.36842105,
       13.63157895, 14.89473684, 16.15789474, 17.42105263, 18.68421053,
       19.94736842, 21.21052632, 22.47368421, 23.73684211, 25.        ])

## Numpy Operation

In [34]:
array2d * 5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
array2d % 2==0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])