In [1]:
import numpy as np

# 1. Convert [ (1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12) ] in a 2d array of 3, 4
# 2. Create a 2D array of 20 elements.
# 3. Create an array from 10, 50 with a step of 5 and convert to 3 possible array shape combinations.

In [2]:
l1=[ (1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12) ]

In [3]:
type(l1)

list

In [4]:
arr1=np.array(l1)

In [5]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
arr0=np.arange(1,21).reshape((4,5))

In [8]:
arr0

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [10]:
np.arange(10,18).reshape(2,2,2)

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

In [11]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(10,50,5).reshape(4,2)

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [13]:
np.arange(10,50,5).reshape(2,4)

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [14]:
np.arange(10,50,5).reshape(2,2,2)

array([[[10, 15],
        [20, 25]],

       [[30, 35],
        [40, 45]]])

In [15]:
mat3=np.arange(5,50,5).reshape((3,3))

In [16]:
bool_arr=mat3%10==0

In [17]:
mat3[bool_arr]

array([10, 20, 30, 40])

In [18]:
multimatrix=np.arange(25).reshape((5,5))

In [19]:
multimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
multimatrix[2:5,2]

array([12, 17, 22])

In [21]:
mat3 = np.arange(5, 50, 5).reshape((3, 3))

In [22]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
bool_arr=mat3%2==0

In [24]:
bool_arr

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [25]:
mat3[bool_arr]

array([10, 20, 30, 40])

In [26]:
mat4=np.arange(1,10).reshape((3,3))

In [27]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
mat3*mat4

array([[  5,  20,  45],
       [ 80, 125, 180],
       [245, 320, 405]])

In [29]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
mat3 @ mat4

array([[150, 180, 210],
       [330, 405, 480],
       [510, 630, 750]])

In [32]:
mat4.min()

1

In [33]:
mat4.max()

9

In [34]:
mat4.mean()

5.0

In [35]:
np.random.random((3,3))

array([[0.11244886, 0.92105771, 0.47074619],
       [0.03904831, 0.15821953, 0.46745727],
       [0.61575416, 0.68415129, 0.26448494]])

In [36]:
np.random.randint(20,30,(3,3))

array([[29, 24, 24],
       [29, 23, 29],
       [23, 20, 27]])

In [37]:
import random

In [38]:
random.randint(1,6)

2

In [39]:
random.choice(['gta','super mario','nfs','contra','duck hund'])


'nfs'

In [40]:
ultimatrix = np.arange(25).reshape((5, 5))

In [41]:
ultimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
ultimatrix[4][4]

24

In [43]:
arr = [[False, True], 
    [True, True, False], 
    [True, False, True]]
print(np.array(arr).astype('int'))

C:\Users\ASUS\AppData\Local\Temp/ipykernel_13660/325595548.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(arr).astype('int'))


ValueError: setting an array element with a sequence.

In [44]:
arr1 = [10, 12, 31]
arr2 = [41, 55, 86]
result = 0
for x, w in zip(arr1, arr2):
    result += x * w
print(result)

3736


In [48]:
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)
print(np.dot(arr1_np, arr2_np))

-1942957984


In [49]:
print(np.array([[[
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]]
    ]]).ndim)

5


In [50]:
arr1 = np.array([[0, 1, 2],
                 [3, 4, 5]])
arr2 = np.array([[6, 7, 8],
                 [9, 10, 11]])
print(np.concatenate((arr1, arr2), axis=1))

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [51]:
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [1, 1, 1, 1, 1],
              [3, 9, 5, 7, 8]])
print(*a[(a[:, 2]>2) & (a[:, 0]>4)][0], sep=", ")

5, 6, 7, 8, 9


In [52]:
arr = np.arange(9).reshape(3, 3)
arr2 = arr[[1, 0, 2], :] @ arr[:, [1, 0, 2]]

In [53]:
arr2

array([[ 54,  42,  66],
       [ 18,  15,  21],
       [ 90,  69, 111]])

In [54]:
arr = np.array([0, 3, 5, 7, 8, 12, 9, 32, 157, 33])
print(sum(arr % 2 == 0) + sum(arr[arr%3 == 0]))

61
